/*
  ==============================================================================

    Values.h
    Created: 18 Dec 2018 6:38:29pm
    Author:  Sébastien Portrait

  ==============================================================================
*/

#pragma once
namespace IDs
{
#define DECLARE_ID(name) const juce::Identifier name (#name);
    
    DECLARE_ID (VOICEMODE)
    DECLARE_ID (VOICENAME)
    DECLARE_ID (COMMONVOLUME)
    DECLARE_ID (COMMONFOOT)
    DECLARE_ID (COMMONMOD)
//AFM ALGO
    DECLARE_ID (AFMALGOELEMENT1)
    DECLARE_ID (AFMALGOELEMENT2)
    DECLARE_ID (AFMALGOELEMENT3)
    DECLARE_ID (AFMALGOELEMENT4)

//AFM OSC
    DECLARE_ID (AFMELEMENT1OSC1)
    DECLARE_ID (AFMELEMENT1OSC2)
    DECLARE_ID (AFMELEMENT1OSC3)
    DECLARE_ID (AFMELEMENT1OSC4)
    DECLARE_ID (AFMELEMENT1OSC5)
    DECLARE_ID (AFMELEMENT1OSC6)

    DECLARE_ID (AFMELEMENT2OSC1)
    DECLARE_ID (AFMELEMENT2OSC2)
    DECLARE_ID (AFMELEMENT2OSC3)
    DECLARE_ID (AFMELEMENT2OSC4)
    DECLARE_ID (AFMELEMENT2OSC5)
    DECLARE_ID (AFMELEMENT2OSC6)
    
    DECLARE_ID (AFMELEMENT3OSC1)
    DECLARE_ID (AFMELEMENT3OSC2)
    DECLARE_ID (AFMELEMENT3OSC3)
    DECLARE_ID (AFMELEMENT3OSC4)
    DECLARE_ID (AFMELEMENT3OSC5)
    DECLARE_ID (AFMELEMENT3OSC6)
    
    DECLARE_ID (AFMELEMENT4OSC1)
    DECLARE_ID (AFMELEMENT4OSC2)
    DECLARE_ID (AFMELEMENT4OSC3)
    DECLARE_ID (AFMELEMENT4OSC4)
    DECLARE_ID (AFMELEMENT4OSC5)
    DECLARE_ID (AFMELEMENT4OSC6)
// AFM Fixed
    DECLARE_ID (AFMELEMENT1OSCFIX1)
    DECLARE_ID (AFMELEMENT1OSCFIX2)
    DECLARE_ID (AFMELEMENT1OSCFIX3)
    DECLARE_ID (AFMELEMENT1OSCFIX4)
    DECLARE_ID (AFMELEMENT1OSCFIX5)
    DECLARE_ID (AFMELEMENT1OSCFIX6)
    
    DECLARE_ID (AFMELEMENT2OSCFIX1)
    DECLARE_ID (AFMELEMENT2OSCFIX2)
    DECLARE_ID (AFMELEMENT2OSCFIX3)
    DECLARE_ID (AFMELEMENT2OSCFIX4)
    DECLARE_ID (AFMELEMENT2OSCFIX5)
    DECLARE_ID (AFMELEMENT2OSCFIX6)
    
    DECLARE_ID (AFMELEMENT3OSCFIX1)
    DECLARE_ID (AFMELEMENT3OSCFIX2)
    DECLARE_ID (AFMELEMENT3OSCFIX3)
    DECLARE_ID (AFMELEMENT3OSCFIX4)
    DECLARE_ID (AFMELEMENT3OSCFIX5)
    DECLARE_ID (AFMELEMENT3OSCFIX6)
    
    DECLARE_ID (AFMELEMENT4OSCFIX1)
    DECLARE_ID (AFMELEMENT4OSCFIX2)
    DECLARE_ID (AFMELEMENT4OSCFIX3)
    DECLARE_ID (AFMELEMENT4OSCFIX4)
    DECLARE_ID (AFMELEMENT4OSCFIX5)
    DECLARE_ID (AFMELEMENT4OSCFIX6)

//
    // AFM Phase Sync
    DECLARE_ID (AFMELEMENT1OSCSYNC1)
    DECLARE_ID (AFMELEMENT1OSCSYNC2)
    DECLARE_ID (AFMELEMENT1OSCSYNC3)
    DECLARE_ID (AFMELEMENT1OSCSYNC4)
    DECLARE_ID (AFMELEMENT1OSCSYNC5)
    DECLARE_ID (AFMELEMENT1OSCSYNC6)
    
    DECLARE_ID (AFMELEMENT2OSCSYNC1)
    DECLARE_ID (AFMELEMENT2OSCSYNC2)
    DECLARE_ID (AFMELEMENT2OSCSYNC3)
    DECLARE_ID (AFMELEMENT2OSCSYNC4)
    DECLARE_ID (AFMELEMENT2OSCSYNC5)
    DECLARE_ID (AFMELEMENT2OSCSYNC6)
    
    DECLARE_ID (AFMELEMENT3OSCSYNC1)
    DECLARE_ID (AFMELEMENT3OSCSYNC2)
    DECLARE_ID (AFMELEMENT3OSCSYNC3)
    DECLARE_ID (AFMELEMENT3OSCSYNC4)
    DECLARE_ID (AFMELEMENT3OSCSYNC5)
    DECLARE_ID (AFMELEMENT3OSCSYNC6)
    
    DECLARE_ID (AFMELEMENT4OSCSYNC1)
    DECLARE_ID (AFMELEMENT4OSCSYNC2)
    DECLARE_ID (AFMELEMENT4OSCSYNC3)
    DECLARE_ID (AFMELEMENT4OSCSYNC4)
    DECLARE_ID (AFMELEMENT4OSCSYNC5)
    DECLARE_ID (AFMELEMENT4OSCSYNC6)

    // AFM operator frequency ratio (Coarse/Fine slider) — drives the FM render
    DECLARE_ID (AFMELEMENT1OSCFINE1)
    DECLARE_ID (AFMELEMENT1OSCFINE2)
    DECLARE_ID (AFMELEMENT1OSCFINE3)
    DECLARE_ID (AFMELEMENT1OSCFINE4)
    DECLARE_ID (AFMELEMENT1OSCFINE5)
    DECLARE_ID (AFMELEMENT1OSCFINE6)

    DECLARE_ID (AFMELEMENT2OSCFINE1)
    DECLARE_ID (AFMELEMENT2OSCFINE2)
    DECLARE_ID (AFMELEMENT2OSCFINE3)
    DECLARE_ID (AFMELEMENT2OSCFINE4)
    DECLARE_ID (AFMELEMENT2OSCFINE5)
    DECLARE_ID (AFMELEMENT2OSCFINE6)

    DECLARE_ID (AFMELEMENT3OSCFINE1)
    DECLARE_ID (AFMELEMENT3OSCFINE2)
    DECLARE_ID (AFMELEMENT3OSCFINE3)
    DECLARE_ID (AFMELEMENT3OSCFINE4)
    DECLARE_ID (AFMELEMENT3OSCFINE5)
    DECLARE_ID (AFMELEMENT3OSCFINE6)

    DECLARE_ID (AFMELEMENT4OSCFINE1)
    DECLARE_ID (AFMELEMENT4OSCFINE2)
    DECLARE_ID (AFMELEMENT4OSCFINE3)
    DECLARE_ID (AFMELEMENT4OSCFINE4)
    DECLARE_ID (AFMELEMENT4OSCFINE5)
    DECLARE_ID (AFMELEMENT4OSCFINE6)

    // AFM operator output level (rendu uniquement — pas encore d'envoi sysex)
    DECLARE_ID (AFMELEMENT1LEVEL1)
    DECLARE_ID (AFMELEMENT1LEVEL2)
    DECLARE_ID (AFMELEMENT1LEVEL3)
    DECLARE_ID (AFMELEMENT1LEVEL4)
    DECLARE_ID (AFMELEMENT1LEVEL5)
    DECLARE_ID (AFMELEMENT1LEVEL6)

    DECLARE_ID (AFMELEMENT2LEVEL1)
    DECLARE_ID (AFMELEMENT2LEVEL2)
    DECLARE_ID (AFMELEMENT2LEVEL3)
    DECLARE_ID (AFMELEMENT2LEVEL4)
    DECLARE_ID (AFMELEMENT2LEVEL5)
    DECLARE_ID (AFMELEMENT2LEVEL6)

    DECLARE_ID (AFMELEMENT3LEVEL1)
    DECLARE_ID (AFMELEMENT3LEVEL2)
    DECLARE_ID (AFMELEMENT3LEVEL3)
    DECLARE_ID (AFMELEMENT3LEVEL4)
    DECLARE_ID (AFMELEMENT3LEVEL5)
    DECLARE_ID (AFMELEMENT3LEVEL6)

    DECLARE_ID (AFMELEMENT4LEVEL1)
    DECLARE_ID (AFMELEMENT4LEVEL2)
    DECLARE_ID (AFMELEMENT4LEVEL3)
    DECLARE_ID (AFMELEMENT4LEVEL4)
    DECLARE_ID (AFMELEMENT4LEVEL5)
    DECLARE_ID (AFMELEMENT4LEVEL6)

    // Sélection de groupe de sortie par élément (Both/1/2/Off via 2 bascules) — rendu seul
    DECLARE_ID (ELEMENT1GROUP1)
    DECLARE_ID (ELEMENT1GROUP2)
    DECLARE_ID (ELEMENT2GROUP1)
    DECLARE_ID (ELEMENT2GROUP2)
    DECLARE_ID (ELEMENT3GROUP1)
    DECLARE_ID (ELEMENT3GROUP2)
    DECLARE_ID (ELEMENT4GROUP1)
    DECLARE_ID (ELEMENT4GROUP2)

    // Section effets (rendu/état seul — structure du manuel : mode + 2 modulation + 2 reverb)
    DECLARE_ID (EFFECTMODE)
    DECLARE_ID (MOD1TYPE)
    DECLARE_ID (MOD1RATE)
    DECLARE_ID (MOD1DEPTH)
    DECLARE_ID (MOD1LEVEL)
    DECLARE_ID (MOD2TYPE)
    DECLARE_ID (MOD2RATE)
    DECLARE_ID (MOD2DEPTH)
    DECLARE_ID (MOD2LEVEL)
    DECLARE_ID (REV1TYPE)
    DECLARE_ID (REV1TIME)
    DECLARE_ID (REV1LEVEL)
    DECLARE_ID (REV2TYPE)
    DECLARE_ID (REV2TIME)
    DECLARE_ID (REV2LEVEL)

//

    DECLARE_ID (ELEMENT1WAVEFORM)
    DECLARE_ID (ELEMENT1PITCH)
    DECLARE_ID (ELEMENT1FINE)
    DECLARE_ID (ELEMENT1FIXED)
    DECLARE_ID (ELEMENT1VOLUME)
    DECLARE_ID (ELEMENT1FQ1)
    DECLARE_ID (ELEMENT1FQ2)
    DECLARE_ID (ELEMENT1MODEFILTRE1)
    DECLARE_ID (ELEMENT1MODEFILTRE2)
    DECLARE_ID (ELEMENT1RESONNANCEFILTRE)
    DECLARE_ID (ELEMENT1VELOCITYFILTRE)
    DECLARE_ID (ELEMENT1LFOFILTRE)
    DECLARE_ID (ELEMENT1SLOPEFILTRE)
        DECLARE_ID (ELEMENT1SLOPEFILTRE2)
    DECLARE_ID (ELEMENT1CONTROLEURFILTRE1)
    DECLARE_ID (ELEMENT1CONTROLEURFILTRE2)
    DECLARE_ID (ELEMENT1EGFILTRELEVEL0)
    DECLARE_ID (ELEMENT1EGFILTRELEVEL1)
    DECLARE_ID (ELEMENT1EGFILTRELEVEL2)
    DECLARE_ID (ELEMENT1EGFILTRELEVEL3)
    DECLARE_ID (ELEMENT1EGFILTRELEVEL4)
    DECLARE_ID (ELEMENT1EGFILTRERL1)
    DECLARE_ID (ELEMENT1EGFILTRERL2)
    DECLARE_ID (ELEMENT1EGFILTRER1)
    DECLARE_ID (ELEMENT1EGFILTRER2)
    DECLARE_ID (ELEMENT1EGFILTRER3)
    DECLARE_ID (ELEMENT1EGFILTRER4)
    DECLARE_ID (ELEMENT1EGFILTRERR1)
    DECLARE_ID (ELEMENT1EGFILTRERR2)
    
    DECLARE_ID (ELEMENT1EGFILTRE2LEVEL0)
    DECLARE_ID (ELEMENT1EGFILTRE2LEVEL1)
    DECLARE_ID (ELEMENT1EGFILTRE2LEVEL2)
    DECLARE_ID (ELEMENT1EGFILTRE2LEVEL3)
    DECLARE_ID (ELEMENT1EGFILTRE2LEVEL4)
    DECLARE_ID (ELEMENT1EGFILTRE2RL1)
    DECLARE_ID (ELEMENT1EGFILTRE2RL2)
    DECLARE_ID (ELEMENT1EGFILTRE2R1)
    DECLARE_ID (ELEMENT1EGFILTRE2R2)
    DECLARE_ID (ELEMENT1EGFILTRE2R3)
    DECLARE_ID (ELEMENT1EGFILTRE2R4)
    DECLARE_ID (ELEMENT1EGFILTRE2RR1)
    DECLARE_ID (ELEMENT1EGFILTRE2RR2)
    
    DECLARE_ID (ELEMENT2WAVEFORM)
    DECLARE_ID (ELEMENT2PITCH)
    DECLARE_ID (ELEMENT2FINE)
    DECLARE_ID (ELEMENT2FIXED)
    DECLARE_ID (ELEMENT2VOLUME)
    DECLARE_ID (ELEMENT2FQ1)
    DECLARE_ID (ELEMENT2FQ2)
    DECLARE_ID (ELEMENT2MODEFILTRE1)
    DECLARE_ID (ELEMENT2MODEFILTRE2)
    DECLARE_ID (ELEMENT2RESONNANCEFILTRE)
    DECLARE_ID (ELEMENT2VELOCITYFILTRE)
    DECLARE_ID (ELEMENT2LFOFILTRE)
    DECLARE_ID (ELEMENT2SLOPEFILTRE)
        DECLARE_ID (ELEMENT2SLOPEFILTRE2)
    DECLARE_ID (ELEMENT2CONTROLEURFILTRE1)
    DECLARE_ID (ELEMENT2CONTROLEURFILTRE2)
    DECLARE_ID (ELEMENT2EGFILTRELEVEL0)
    DECLARE_ID (ELEMENT2EGFILTRELEVEL1)
    DECLARE_ID (ELEMENT2EGFILTRELEVEL2)
    DECLARE_ID (ELEMENT2EGFILTRELEVEL3)
    DECLARE_ID (ELEMENT2EGFILTRELEVEL4)
    DECLARE_ID (ELEMENT2EGFILTRERL1)
    DECLARE_ID (ELEMENT2EGFILTRERL2)
    DECLARE_ID (ELEMENT2EGFILTRER1)
    DECLARE_ID (ELEMENT2EGFILTRER2)
    DECLARE_ID (ELEMENT2EGFILTRER3)
    DECLARE_ID (ELEMENT2EGFILTRER4)
    DECLARE_ID (ELEMENT2EGFILTRERR1)
    DECLARE_ID (ELEMENT2EGFILTRERR2)
    
    DECLARE_ID (ELEMENT2EGFILTRE2LEVEL0)
    DECLARE_ID (ELEMENT2EGFILTRE2LEVEL1)
    DECLARE_ID (ELEMENT2EGFILTRE2LEVEL2)
    DECLARE_ID (ELEMENT2EGFILTRE2LEVEL3)
    DECLARE_ID (ELEMENT2EGFILTRE2LEVEL4)
    DECLARE_ID (ELEMENT2EGFILTRE2RL1)
    DECLARE_ID (ELEMENT2EGFILTRE2RL2)
    DECLARE_ID (ELEMENT2EGFILTRE2R1)
    DECLARE_ID (ELEMENT2EGFILTRE2R2)
    DECLARE_ID (ELEMENT2EGFILTRE2R3)
    DECLARE_ID (ELEMENT2EGFILTRE2R4)
    DECLARE_ID (ELEMENT2EGFILTRE2RR1)
    DECLARE_ID (ELEMENT2EGFILTRE2RR2)
    
    DECLARE_ID (ELEMENT3WAVEFORM)
    DECLARE_ID (ELEMENT3PITCH)
    DECLARE_ID (ELEMENT3FINE)
    DECLARE_ID (ELEMENT3FIXED)
    DECLARE_ID (ELEMENT3VOLUME)
    DECLARE_ID (ELEMENT3FQ1)
    DECLARE_ID (ELEMENT3FQ2)
    DECLARE_ID (ELEMENT3MODEFILTRE1)
    DECLARE_ID (ELEMENT3MODEFILTRE2)
    DECLARE_ID (ELEMENT3RESONNANCEFILTRE)
    DECLARE_ID (ELEMENT3VELOCITYFILTRE)
    DECLARE_ID (ELEMENT3LFOFILTRE)
    DECLARE_ID (ELEMENT3SLOPEFILTRE)
        DECLARE_ID (ELEMENT3SLOPEFILTRE2)
    DECLARE_ID (ELEMENT3CONTROLEURFILTRE1)
    DECLARE_ID (ELEMENT3CONTROLEURFILTRE2)
    DECLARE_ID (ELEMENT3EGFILTRELEVEL0)
    DECLARE_ID (ELEMENT3EGFILTRELEVEL1)
    DECLARE_ID (ELEMENT3EGFILTRELEVEL2)
    DECLARE_ID (ELEMENT3EGFILTRELEVEL3)
    DECLARE_ID (ELEMENT3EGFILTRELEVEL4)
    DECLARE_ID (ELEMENT3EGFILTRERL1)
    DECLARE_ID (ELEMENT3EGFILTRERL2)
    DECLARE_ID (ELEMENT3EGFILTRER1)
    DECLARE_ID (ELEMENT3EGFILTRER2)
    DECLARE_ID (ELEMENT3EGFILTRER3)
    DECLARE_ID (ELEMENT3EGFILTRER4)
    DECLARE_ID (ELEMENT3EGFILTRERR1)
    DECLARE_ID (ELEMENT3EGFILTRERR2)
    
    DECLARE_ID (ELEMENT3EGFILTRE2LEVEL0)
    DECLARE_ID (ELEMENT3EGFILTRE2LEVEL1)
    DECLARE_ID (ELEMENT3EGFILTRE2LEVEL2)
    DECLARE_ID (ELEMENT3EGFILTRE2LEVEL3)
    DECLARE_ID (ELEMENT3EGFILTRE2LEVEL4)
    DECLARE_ID (ELEMENT3EGFILTRE2RL1)
    DECLARE_ID (ELEMENT3EGFILTRE2RL2)
    DECLARE_ID (ELEMENT3EGFILTRE2R1)
    DECLARE_ID (ELEMENT3EGFILTRE2R2)
    DECLARE_ID (ELEMENT3EGFILTRE2R3)
    DECLARE_ID (ELEMENT3EGFILTRE2R4)
    DECLARE_ID (ELEMENT3EGFILTRE2RR1)
    DECLARE_ID (ELEMENT3EGFILTRE2RR2)
    
    DECLARE_ID (ELEMENT4WAVEFORM)
    DECLARE_ID (ELEMENT4PITCH)
    DECLARE_ID (ELEMENT4FINE)
    DECLARE_ID (ELEMENT4FIXED)
    DECLARE_ID (ELEMENT4VOLUME)
    DECLARE_ID (ELEMENT4FQ1)
    DECLARE_ID (ELEMENT4FQ2)
    DECLARE_ID (ELEMENT4MODEFILTRE1)
    DECLARE_ID (ELEMENT4MODEFILTRE2)
    DECLARE_ID (ELEMENT4RESONNANCEFILTRE)
    DECLARE_ID (ELEMENT4VELOCITYFILTRE)
    DECLARE_ID (ELEMENT4LFOFILTRE)
    DECLARE_ID (ELEMENT4SLOPEFILTRE)
        DECLARE_ID (ELEMENT4SLOPEFILTRE2)
    DECLARE_ID (ELEMENT4CONTROLEURFILTRE1)
    DECLARE_ID (ELEMENT4CONTROLEURFILTRE2)
    DECLARE_ID (ELEMENT4EGFILTRELEVEL0)
    DECLARE_ID (ELEMENT4EGFILTRELEVEL1)
    DECLARE_ID (ELEMENT4EGFILTRELEVEL2)
    DECLARE_ID (ELEMENT4EGFILTRELEVEL3)
    DECLARE_ID (ELEMENT4EGFILTRELEVEL4)
    DECLARE_ID (ELEMENT4EGFILTRERL1)
    DECLARE_ID (ELEMENT4EGFILTRERL2)
    DECLARE_ID (ELEMENT4EGFILTRER1)
    DECLARE_ID (ELEMENT4EGFILTRER2)
    DECLARE_ID (ELEMENT4EGFILTRER3)
    DECLARE_ID (ELEMENT4EGFILTRER4)
    DECLARE_ID (ELEMENT4EGFILTRERR1)
    DECLARE_ID (ELEMENT4EGFILTRERR2)
    
    DECLARE_ID (ELEMENT4EGFILTRE2LEVEL0)
    DECLARE_ID (ELEMENT4EGFILTRE2LEVEL1)
    DECLARE_ID (ELEMENT4EGFILTRE2LEVEL2)
    DECLARE_ID (ELEMENT4EGFILTRE2LEVEL3)
    DECLARE_ID (ELEMENT4EGFILTRE2LEVEL4)
    DECLARE_ID (ELEMENT4EGFILTRE2RL1)
    DECLARE_ID (ELEMENT4EGFILTRE2RL2)
    DECLARE_ID (ELEMENT4EGFILTRE2R1)
    DECLARE_ID (ELEMENT4EGFILTRE2R2)
    DECLARE_ID (ELEMENT4EGFILTRE2R3)
    DECLARE_ID (ELEMENT4EGFILTRE2R4)
    DECLARE_ID (ELEMENT4EGFILTRE2RR1)
    DECLARE_ID (ELEMENT4EGFILTRE2RR2)

    // EG de VOLUME (amplitude) — stockage propre, distinct de l'EG de filtre.
    DECLARE_ID (ELEMENT1SLOPEVOL)
    DECLARE_ID (ELEMENT1EGVOLLEVEL0) DECLARE_ID (ELEMENT1EGVOLLEVEL1) DECLARE_ID (ELEMENT1EGVOLLEVEL2)
    DECLARE_ID (ELEMENT1EGVOLLEVEL3) DECLARE_ID (ELEMENT1EGVOLLEVEL4)
    DECLARE_ID (ELEMENT1EGVOLRL1) DECLARE_ID (ELEMENT1EGVOLRL2)
    DECLARE_ID (ELEMENT1EGVOLR1) DECLARE_ID (ELEMENT1EGVOLR2) DECLARE_ID (ELEMENT1EGVOLR3) DECLARE_ID (ELEMENT1EGVOLR4)
    DECLARE_ID (ELEMENT1EGVOLRR1) DECLARE_ID (ELEMENT1EGVOLRR2)

    DECLARE_ID (ELEMENT2SLOPEVOL)
    DECLARE_ID (ELEMENT2EGVOLLEVEL0) DECLARE_ID (ELEMENT2EGVOLLEVEL1) DECLARE_ID (ELEMENT2EGVOLLEVEL2)
    DECLARE_ID (ELEMENT2EGVOLLEVEL3) DECLARE_ID (ELEMENT2EGVOLLEVEL4)
    DECLARE_ID (ELEMENT2EGVOLRL1) DECLARE_ID (ELEMENT2EGVOLRL2)
    DECLARE_ID (ELEMENT2EGVOLR1) DECLARE_ID (ELEMENT2EGVOLR2) DECLARE_ID (ELEMENT2EGVOLR3) DECLARE_ID (ELEMENT2EGVOLR4)
    DECLARE_ID (ELEMENT2EGVOLRR1) DECLARE_ID (ELEMENT2EGVOLRR2)

    DECLARE_ID (ELEMENT3SLOPEVOL)
    DECLARE_ID (ELEMENT3EGVOLLEVEL0) DECLARE_ID (ELEMENT3EGVOLLEVEL1) DECLARE_ID (ELEMENT3EGVOLLEVEL2)
    DECLARE_ID (ELEMENT3EGVOLLEVEL3) DECLARE_ID (ELEMENT3EGVOLLEVEL4)
    DECLARE_ID (ELEMENT3EGVOLRL1) DECLARE_ID (ELEMENT3EGVOLRL2)
    DECLARE_ID (ELEMENT3EGVOLR1) DECLARE_ID (ELEMENT3EGVOLR2) DECLARE_ID (ELEMENT3EGVOLR3) DECLARE_ID (ELEMENT3EGVOLR4)
    DECLARE_ID (ELEMENT3EGVOLRR1) DECLARE_ID (ELEMENT3EGVOLRR2)

    DECLARE_ID (ELEMENT4SLOPEVOL)
    DECLARE_ID (ELEMENT4EGVOLLEVEL0) DECLARE_ID (ELEMENT4EGVOLLEVEL1) DECLARE_ID (ELEMENT4EGVOLLEVEL2)
    DECLARE_ID (ELEMENT4EGVOLLEVEL3) DECLARE_ID (ELEMENT4EGVOLLEVEL4)
    DECLARE_ID (ELEMENT4EGVOLRL1) DECLARE_ID (ELEMENT4EGVOLRL2)
    DECLARE_ID (ELEMENT4EGVOLR1) DECLARE_ID (ELEMENT4EGVOLR2) DECLARE_ID (ELEMENT4EGVOLR3) DECLARE_ID (ELEMENT4EGVOLR4)
    DECLARE_ID (ELEMENT4EGVOLRR1) DECLARE_ID (ELEMENT4EGVOLRR2)

#undef DECLARE_ID
}
/*
Value valueVoiceMode; // mode 1AFM, 2AFM, ...
//Filter Values
Value valueFilter1FreqElement1;
Value valueFilter1FreqElement2;
Value valueFilter1FreqElement3;
Value valueFilter1FreqElement4;

Value valueFilter2FreqElement1;
Value valueFilter2FreqElement2;
Value valueFilter2FreqElement3;
Value valueFilter2FreqElement4;

Value valueFilterResonnanceElement1;
Value valueFilterResonnanceElement2;
Value valueFilterResonnanceElement3;
Value valueFilterResonnanceElement4;

Value valueFilterLfoElement1;
Value valueFilterLfoElement2;
Value valueFilterLfoElement3;
Value valueFilterLfoElement4;

Value valueFilterVelocityElement1;
Value valueFilterVelocityElement2;
Value valueFilterVelocityElement3;
Value valueFilterVelocityElement4;

Value valueFilterSlopeElement1;
Value valueFilterSlopeElement2;
Value valueFilterSlopeElement3;
Value valueFilterSlopeElement4;

Value valueFilter1ModeElement1;
Value valueFilter1ModeElement2;
Value valueFilter1ModeElement3;
Value valueFilter1ModeElement4;

Value valueFilter2ModeElement1;
Value valueFilter2ModeElement2;
Value valueFilter2ModeElement3;
Value valueFilter2ModeElement4;

Value valueFilter1ControlElement1;
Value valueFilter1ControlElement2;
Value valueFilter1ControlElement3;
Value valueFilter1ControlElement4;

Value valueFilter2ControlElement1;
Value valueFilter2ControlElement2;
Value valueFilter2ControlElement3;
Value valueFilter2ControlElement4;

Value valueFilterLevel0Element1;
Value valueFilterLevel0Element2;
Value valueFilterLevel0Element3;
Value valueFilterLevel0Element4;

Value valueFilterLevel1Element1;
Value valueFilterLevel1Element2;
Value valueFilterLevel1Element3;
Value valueFilterLevel1Element4;

Value valueFilterLevel2Element1;
Value valueFilterLevel2Element2;
Value valueFilterLevel2Element3;
Value valueFilterLevel2Element4;

Value valueFilterLevel3Element1;
Value valueFilterLevel3Element2;
Value valueFilterLevel3Element3;
Value valueFilterLevel3Element4;

Value valueFilterLevel4Element1;
Value valueFilterLevel4Element2;
Value valueFilterLevel4Element3;
Value valueFilterLevel4Element4;

Value valueFilterRate0Element1;
Value valueFilterRate0Element2;
Value valueFilterRate0Element3;
Value valueFilterRate0Element4;

Value valueFilterRate1Element1;
Value valueFilterRate1Element2;
Value valueFilterRate1Element3;
Value valueFilterRate1Element4;
*/
// `inline` : défini dans un header mais une seule instance (ODR-safe, multi-TU/CMake).
inline ValueTree   valueTreeVoice ("Sysex77");
