/*
  ==============================================================================

    Values.h
    Created: 18 Dec 2018 6:38:29pm
    Author:  Sébastien Portrait

  ==============================================================================
*/

#pragma once
namespace IDs
{
#define DECLARE_ID(name) const juce::Identifier name (#name);
    
    DECLARE_ID (VOICEMODE)
    DECLARE_ID (VOICENAME)
    DECLARE_ID (COMMONVOLUME)
    DECLARE_ID (COMMONFOOT)
    DECLARE_ID (COMMONMOD)
//AFM ALGO
    DECLARE_ID (AFMALGOELEMENT1)
    DECLARE_ID (AFMALGOELEMENT2)
    DECLARE_ID (AFMALGOELEMENT3)
    DECLARE_ID (AFMALGOELEMENT4)

//AFM OSC
    DECLARE_ID (AFMELEMENT1OSC1)
    DECLARE_ID (AFMELEMENT1OSC2)
    DECLARE_ID (AFMELEMENT1OSC3)
    DECLARE_ID (AFMELEMENT1OSC4)
    DECLARE_ID (AFMELEMENT1OSC5)
    DECLARE_ID (AFMELEMENT1OSC6)

    DECLARE_ID (AFMELEMENT2OSC1)
    DECLARE_ID (AFMELEMENT2OSC2)
    DECLARE_ID (AFMELEMENT2OSC3)
    DECLARE_ID (AFMELEMENT2OSC4)
    DECLARE_ID (AFMELEMENT2OSC5)
    DECLARE_ID (AFMELEMENT2OSC6)
    
    DECLARE_ID (AFMELEMENT3OSC1)
    DECLARE_ID (AFMELEMENT3OSC2)
    DECLARE_ID (AFMELEMENT3OSC3)
    DECLARE_ID (AFMELEMENT3OSC4)
    DECLARE_ID (AFMELEMENT3OSC5)
    DECLARE_ID (AFMELEMENT3OSC6)
    
    DECLARE_ID (AFMELEMENT4OSC1)
    DECLARE_ID (AFMELEMENT4OSC2)
    DECLARE_ID (AFMELEMENT4OSC3)
    DECLARE_ID (AFMELEMENT4OSC4)
    DECLARE_ID (AFMELEMENT4OSC5)
    DECLARE_ID (AFMELEMENT4OSC6)
// AFM Fixed
    DECLARE_ID (AFMELEMENT1OSCFIX1)
    DECLARE_ID (AFMELEMENT1OSCFIX2)
    DECLARE_ID (AFMELEMENT1OSCFIX3)
    DECLARE_ID (AFMELEMENT1OSCFIX4)
    DECLARE_ID (AFMELEMENT1OSCFIX5)
    DECLARE_ID (AFMELEMENT1OSCFIX6)
    
    DECLARE_ID (AFMELEMENT2OSCFIX1)
    DECLARE_ID (AFMELEMENT2OSCFIX2)
    DECLARE_ID (AFMELEMENT2OSCFIX3)
    DECLARE_ID (AFMELEMENT2OSCFIX4)
    DECLARE_ID (AFMELEMENT2OSCFIX5)
    DECLARE_ID (AFMELEMENT2OSCFIX6)
    
    DECLARE_ID (AFMELEMENT3OSCFIX1)
    DECLARE_ID (AFMELEMENT3OSCFIX2)
    DECLARE_ID (AFMELEMENT3OSCFIX3)
    DECLARE_ID (AFMELEMENT3OSCFIX4)
    DECLARE_ID (AFMELEMENT3OSCFIX5)
    DECLARE_ID (AFMELEMENT3OSCFIX6)
    
    DECLARE_ID (AFMELEMENT4OSCFIX1)
    DECLARE_ID (AFMELEMENT4OSCFIX2)
    DECLARE_ID (AFMELEMENT4OSCFIX3)
    DECLARE_ID (AFMELEMENT4OSCFIX4)
    DECLARE_ID (AFMELEMENT4OSCFIX5)
    DECLARE_ID (AFMELEMENT4OSCFIX6)

//
    // AFM Phase Sync
    DECLARE_ID (AFMELEMENT1OSCSYNC1)
    DECLARE_ID (AFMELEMENT1OSCSYNC2)
    DECLARE_ID (AFMELEMENT1OSCSYNC3)
    DECLARE_ID (AFMELEMENT1OSCSYNC4)
    DECLARE_ID (AFMELEMENT1OSCSYNC5)
    DECLARE_ID (AFMELEMENT1OSCSYNC6)
    
    DECLARE_ID (AFMELEMENT2OSCSYNC1)
    DECLARE_ID (AFMELEMENT2OSCSYNC2)
    DECLARE_ID (AFMELEMENT2OSCSYNC3)
    DECLARE_ID (AFMELEMENT2OSCSYNC4)
    DECLARE_ID (AFMELEMENT2OSCSYNC5)
    DECLARE_ID (AFMELEMENT2OSCSYNC6)
    
    DECLARE_ID (AFMELEMENT3OSCSYNC1)
    DECLARE_ID (AFMELEMENT3OSCSYNC2)
    DECLARE_ID (AFMELEMENT3OSCSYNC3)
    DECLARE_ID (AFMELEMENT3OSCSYNC4)
    DECLARE_ID (AFMELEMENT3OSCSYNC5)
    DECLARE_ID (AFMELEMENT3OSCSYNC6)
    
    DECLARE_ID (AFMELEMENT4OSCSYNC1)
    DECLARE_ID (AFMELEMENT4OSCSYNC2)
    DECLARE_ID (AFMELEMENT4OSCSYNC3)
    DECLARE_ID (AFMELEMENT4OSCSYNC4)
    DECLARE_ID (AFMELEMENT4OSCSYNC5)
    DECLARE_ID (AFMELEMENT4OSCSYNC6)

    // AFM operator frequency ratio (Coarse/Fine slider) — drives the FM render
    DECLARE_ID (AFMELEMENT1OSCFINE1)
    DECLARE_ID (AFMELEMENT1OSCFINE2)
    DECLARE_ID (AFMELEMENT1OSCFINE3)
    DECLARE_ID (AFMELEMENT1OSCFINE4)
    DECLARE_ID (AFMELEMENT1OSCFINE5)
    DECLARE_ID (AFMELEMENT1OSCFINE6)

    DECLARE_ID (AFMELEMENT2OSCFINE1)
    DECLARE_ID (AFMELEMENT2OSCFINE2)
    DECLARE_ID (AFMELEMENT2OSCFINE3)
    DECLARE_ID (AFMELEMENT2OSCFINE4)
    DECLARE_ID (AFMELEMENT2OSCFINE5)
    DECLARE_ID (AFMELEMENT2OSCFINE6)

    DECLARE_ID (AFMELEMENT3OSCFINE1)
    DECLARE_ID (AFMELEMENT3OSCFINE2)
    DECLARE_ID (AFMELEMENT3OSCFINE3)
    DECLARE_ID (AFMELEMENT3OSCFINE4)
    DECLARE_ID (AFMELEMENT3OSCFINE5)
    DECLARE_ID (AFMELEMENT3OSCFINE6)

    DECLARE_ID (AFMELEMENT4OSCFINE1)
    DECLARE_ID (AFMELEMENT4OSCFINE2)
    DECLARE_ID (AFMELEMENT4OSCFINE3)
    DECLARE_ID (AFMELEMENT4OSCFINE4)
    DECLARE_ID (AFMELEMENT4OSCFINE5)
    DECLARE_ID (AFMELEMENT4OSCFINE6)

    // AFM operator output level (rendu uniquement — pas encore d'envoi sysex)
    DECLARE_ID (AFMELEMENT1LEVEL1)
    DECLARE_ID (AFMELEMENT1LEVEL2)
    DECLARE_ID (AFMELEMENT1LEVEL3)
    DECLARE_ID (AFMELEMENT1LEVEL4)
    DECLARE_ID (AFMELEMENT1LEVEL5)
    DECLARE_ID (AFMELEMENT1LEVEL6)

    DECLARE_ID (AFMELEMENT2LEVEL1)
    DECLARE_ID (AFMELEMENT2LEVEL2)
    DECLARE_ID (AFMELEMENT2LEVEL3)
    DECLARE_ID (AFMELEMENT2LEVEL4)
    DECLARE_ID (AFMELEMENT2LEVEL5)
    DECLARE_ID (AFMELEMENT2LEVEL6)

    DECLARE_ID (AFMELEMENT3LEVEL1)
    DECLARE_ID (AFMELEMENT3LEVEL2)
    DECLARE_ID (AFMELEMENT3LEVEL3)
    DECLARE_ID (AFMELEMENT3LEVEL4)
    DECLARE_ID (AFMELEMENT3LEVEL5)
    DECLARE_ID (AFMELEMENT3LEVEL6)

    DECLARE_ID (AFMELEMENT4LEVEL1)
    DECLARE_ID (AFMELEMENT4LEVEL2)
    DECLARE_ID (AFMELEMENT4LEVEL3)
    DECLARE_ID (AFMELEMENT4LEVEL4)
    DECLARE_ID (AFMELEMENT4LEVEL5)
    DECLARE_ID (AFMELEMENT4LEVEL6)

    // Sélection de groupe de sortie par élément (Both/1/2/Off via 2 bascules) — rendu seul
    DECLARE_ID (ELEMENT1GROUP1)
    DECLARE_ID (ELEMENT1GROUP2)
    DECLARE_ID (ELEMENT2GROUP1)
    DECLARE_ID (ELEMENT2GROUP2)
    DECLARE_ID (ELEMENT3GROUP1)
    DECLARE_ID (ELEMENT3GROUP2)
    DECLARE_ID (ELEMENT4GROUP1)
    DECLARE_ID (ELEMENT4GROUP2)

    // Section effets — adresses RÉELLES (groupe 0x08, Table 1-9 / map TG77 vérifiée).
    // N2 = offset commenté ; 2 unités Chorus (type+bal+level+4 prm) + 2 unités Reverb (…+3 prm).
    DECLARE_ID (EFFECTMODE)   // N2 0x00 (0-3)
    DECLARE_ID (CHR1TYPE)     // 0x01 (0-4)
    DECLARE_ID (CHR1BAL)      // 0x02 (0-100)
    DECLARE_ID (CHR1LVL)      // 0x03 (0-100)
    DECLARE_ID (CHR1PRM1)     // 0x04
    DECLARE_ID (CHR1PRM2)     // 0x05
    DECLARE_ID (CHR1PRM3)     // 0x06
    DECLARE_ID (CHR1PRM4)     // 0x07
    DECLARE_ID (CHR2TYPE)     // 0x08 (0-4)
    DECLARE_ID (CHR2BAL)      // 0x09
    DECLARE_ID (CHR2LVL)      // 0x0A
    DECLARE_ID (CHR2PRM1)     // 0x0B
    DECLARE_ID (CHR2PRM2)     // 0x0C
    DECLARE_ID (CHR2PRM3)     // 0x0D
    DECLARE_ID (CHR2PRM4)     // 0x0E
    DECLARE_ID (REV1TYPE)     // 0x0F (0-40)
    DECLARE_ID (REV1BAL)      // 0x10
    DECLARE_ID (REV1LVL)      // 0x11
    DECLARE_ID (REV1PRM1)     // 0x12
    DECLARE_ID (REV1PRM2)     // 0x13
    DECLARE_ID (REV1PRM3)     // 0x14
    DECLARE_ID (REV2TYPE)     // 0x15 (0-40)
    DECLARE_ID (REV2BAL)      // 0x16
    DECLARE_ID (REV2LVL)      // 0x17
    DECLARE_ID (REV2PRM1)     // 0x18
    DECLARE_ID (REV2PRM2)     // 0x19
    DECLARE_ID (REV2PRM3)     // 0x1A
    DECLARE_ID (STMIX1)       // 0x1B (0-1)
    DECLARE_ID (STMIX2)       // 0x1C (0-1)

//

    DECLARE_ID (ELEMENT1WAVEFORM)
    DECLARE_ID (ELEMENT1PITCH)
    DECLARE_ID (ELEMENT1FINE)
    DECLARE_ID (ELEMENT1FIXED)
    DECLARE_ID (ELEMENT1VOLUME)
    DECLARE_ID (ELEMENT1FQ1)
    DECLARE_ID (ELEMENT1FQ2)
    DECLARE_ID (ELEMENT1MODEFILTRE1)
    DECLARE_ID (ELEMENT1MODEFILTRE2)
    DECLARE_ID (ELEMENT1RESONNANCEFILTRE)
    DECLARE_ID (ELEMENT1VELOCITYFILTRE)
    DECLARE_ID (ELEMENT1LFOFILTRE)
    DECLARE_ID (ELEMENT1SLOPEFILTRE)
        DECLARE_ID (ELEMENT1SLOPEFILTRE2)
    DECLARE_ID (ELEMENT1CONTROLEURFILTRE1)
    DECLARE_ID (ELEMENT1CONTROLEURFILTRE2)
    DECLARE_ID (ELEMENT1EGFILTRELEVEL0)
    DECLARE_ID (ELEMENT1EGFILTRELEVEL1)
    DECLARE_ID (ELEMENT1EGFILTRELEVEL2)
    DECLARE_ID (ELEMENT1EGFILTRELEVEL3)
    DECLARE_ID (ELEMENT1EGFILTRELEVEL4)
    DECLARE_ID (ELEMENT1EGFILTRERL1)
    DECLARE_ID (ELEMENT1EGFILTRERL2)
    DECLARE_ID (ELEMENT1EGFILTRER1)
    DECLARE_ID (ELEMENT1EGFILTRER2)
    DECLARE_ID (ELEMENT1EGFILTRER3)
    DECLARE_ID (ELEMENT1EGFILTRER4)
    DECLARE_ID (ELEMENT1EGFILTRERR1)
    DECLARE_ID (ELEMENT1EGFILTRERR2)
    
    DECLARE_ID (ELEMENT1EGFILTRE2LEVEL0)
    DECLARE_ID (ELEMENT1EGFILTRE2LEVEL1)
    DECLARE_ID (ELEMENT1EGFILTRE2LEVEL2)
    DECLARE_ID (ELEMENT1EGFILTRE2LEVEL3)
    DECLARE_ID (ELEMENT1EGFILTRE2LEVEL4)
    DECLARE_ID (ELEMENT1EGFILTRE2RL1)
    DECLARE_ID (ELEMENT1EGFILTRE2RL2)
    DECLARE_ID (ELEMENT1EGFILTRE2R1)
    DECLARE_ID (ELEMENT1EGFILTRE2R2)
    DECLARE_ID (ELEMENT1EGFILTRE2R3)
    DECLARE_ID (ELEMENT1EGFILTRE2R4)
    DECLARE_ID (ELEMENT1EGFILTRE2RR1)
    DECLARE_ID (ELEMENT1EGFILTRE2RR2)
    
    DECLARE_ID (ELEMENT2WAVEFORM)
    DECLARE_ID (ELEMENT2PITCH)
    DECLARE_ID (ELEMENT2FINE)
    DECLARE_ID (ELEMENT2FIXED)
    DECLARE_ID (ELEMENT2VOLUME)
    DECLARE_ID (ELEMENT2FQ1)
    DECLARE_ID (ELEMENT2FQ2)
    DECLARE_ID (ELEMENT2MODEFILTRE1)
    DECLARE_ID (ELEMENT2MODEFILTRE2)
    DECLARE_ID (ELEMENT2RESONNANCEFILTRE)
    DECLARE_ID (ELEMENT2VELOCITYFILTRE)
    DECLARE_ID (ELEMENT2LFOFILTRE)
    DECLARE_ID (ELEMENT2SLOPEFILTRE)
        DECLARE_ID (ELEMENT2SLOPEFILTRE2)
    DECLARE_ID (ELEMENT2CONTROLEURFILTRE1)
    DECLARE_ID (ELEMENT2CONTROLEURFILTRE2)
    DECLARE_ID (ELEMENT2EGFILTRELEVEL0)
    DECLARE_ID (ELEMENT2EGFILTRELEVEL1)
    DECLARE_ID (ELEMENT2EGFILTRELEVEL2)
    DECLARE_ID (ELEMENT2EGFILTRELEVEL3)
    DECLARE_ID (ELEMENT2EGFILTRELEVEL4)
    DECLARE_ID (ELEMENT2EGFILTRERL1)
    DECLARE_ID (ELEMENT2EGFILTRERL2)
    DECLARE_ID (ELEMENT2EGFILTRER1)
    DECLARE_ID (ELEMENT2EGFILTRER2)
    DECLARE_ID (ELEMENT2EGFILTRER3)
    DECLARE_ID (ELEMENT2EGFILTRER4)
    DECLARE_ID (ELEMENT2EGFILTRERR1)
    DECLARE_ID (ELEMENT2EGFILTRERR2)
    
    DECLARE_ID (ELEMENT2EGFILTRE2LEVEL0)
    DECLARE_ID (ELEMENT2EGFILTRE2LEVEL1)
    DECLARE_ID (ELEMENT2EGFILTRE2LEVEL2)
    DECLARE_ID (ELEMENT2EGFILTRE2LEVEL3)
    DECLARE_ID (ELEMENT2EGFILTRE2LEVEL4)
    DECLARE_ID (ELEMENT2EGFILTRE2RL1)
    DECLARE_ID (ELEMENT2EGFILTRE2RL2)
    DECLARE_ID (ELEMENT2EGFILTRE2R1)
    DECLARE_ID (ELEMENT2EGFILTRE2R2)
    DECLARE_ID (ELEMENT2EGFILTRE2R3)
    DECLARE_ID (ELEMENT2EGFILTRE2R4)
    DECLARE_ID (ELEMENT2EGFILTRE2RR1)
    DECLARE_ID (ELEMENT2EGFILTRE2RR2)
    
    DECLARE_ID (ELEMENT3WAVEFORM)
    DECLARE_ID (ELEMENT3PITCH)
    DECLARE_ID (ELEMENT3FINE)
    DECLARE_ID (ELEMENT3FIXED)
    DECLARE_ID (ELEMENT3VOLUME)
    DECLARE_ID (ELEMENT3FQ1)
    DECLARE_ID (ELEMENT3FQ2)
    DECLARE_ID (ELEMENT3MODEFILTRE1)
    DECLARE_ID (ELEMENT3MODEFILTRE2)
    DECLARE_ID (ELEMENT3RESONNANCEFILTRE)
    DECLARE_ID (ELEMENT3VELOCITYFILTRE)
    DECLARE_ID (ELEMENT3LFOFILTRE)
    DECLARE_ID (ELEMENT3SLOPEFILTRE)
        DECLARE_ID (ELEMENT3SLOPEFILTRE2)
    DECLARE_ID (ELEMENT3CONTROLEURFILTRE1)
    DECLARE_ID (ELEMENT3CONTROLEURFILTRE2)
    DECLARE_ID (ELEMENT3EGFILTRELEVEL0)
    DECLARE_ID (ELEMENT3EGFILTRELEVEL1)
    DECLARE_ID (ELEMENT3EGFILTRELEVEL2)
    DECLARE_ID (ELEMENT3EGFILTRELEVEL3)
    DECLARE_ID (ELEMENT3EGFILTRELEVEL4)
    DECLARE_ID (ELEMENT3EGFILTRERL1)
    DECLARE_ID (ELEMENT3EGFILTRERL2)
    DECLARE_ID (ELEMENT3EGFILTRER1)
    DECLARE_ID (ELEMENT3EGFILTRER2)
    DECLARE_ID (ELEMENT3EGFILTRER3)
    DECLARE_ID (ELEMENT3EGFILTRER4)
    DECLARE_ID (ELEMENT3EGFILTRERR1)
    DECLARE_ID (ELEMENT3EGFILTRERR2)
    
    DECLARE_ID (ELEMENT3EGFILTRE2LEVEL0)
    DECLARE_ID (ELEMENT3EGFILTRE2LEVEL1)
    DECLARE_ID (ELEMENT3EGFILTRE2LEVEL2)
    DECLARE_ID (ELEMENT3EGFILTRE2LEVEL3)
    DECLARE_ID (ELEMENT3EGFILTRE2LEVEL4)
    DECLARE_ID (ELEMENT3EGFILTRE2RL1)
    DECLARE_ID (ELEMENT3EGFILTRE2RL2)
    DECLARE_ID (ELEMENT3EGFILTRE2R1)
    DECLARE_ID (ELEMENT3EGFILTRE2R2)
    DECLARE_ID (ELEMENT3EGFILTRE2R3)
    DECLARE_ID (ELEMENT3EGFILTRE2R4)
    DECLARE_ID (ELEMENT3EGFILTRE2RR1)
    DECLARE_ID (ELEMENT3EGFILTRE2RR2)
    
    DECLARE_ID (ELEMENT4WAVEFORM)
    DECLARE_ID (ELEMENT4PITCH)
    DECLARE_ID (ELEMENT4FINE)
    DECLARE_ID (ELEMENT4FIXED)
    DECLARE_ID (ELEMENT4VOLUME)
    DECLARE_ID (ELEMENT4FQ1)
    DECLARE_ID (ELEMENT4FQ2)
    DECLARE_ID (ELEMENT4MODEFILTRE1)
    DECLARE_ID (ELEMENT4MODEFILTRE2)
    DECLARE_ID (ELEMENT4RESONNANCEFILTRE)
    DECLARE_ID (ELEMENT4VELOCITYFILTRE)
    DECLARE_ID (ELEMENT4LFOFILTRE)
    DECLARE_ID (ELEMENT4SLOPEFILTRE)
        DECLARE_ID (ELEMENT4SLOPEFILTRE2)
    DECLARE_ID (ELEMENT4CONTROLEURFILTRE1)
    DECLARE_ID (ELEMENT4CONTROLEURFILTRE2)
    DECLARE_ID (ELEMENT4EGFILTRELEVEL0)
    DECLARE_ID (ELEMENT4EGFILTRELEVEL1)
    DECLARE_ID (ELEMENT4EGFILTRELEVEL2)
    DECLARE_ID (ELEMENT4EGFILTRELEVEL3)
    DECLARE_ID (ELEMENT4EGFILTRELEVEL4)
    DECLARE_ID (ELEMENT4EGFILTRERL1)
    DECLARE_ID (ELEMENT4EGFILTRERL2)
    DECLARE_ID (ELEMENT4EGFILTRER1)
    DECLARE_ID (ELEMENT4EGFILTRER2)
    DECLARE_ID (ELEMENT4EGFILTRER3)
    DECLARE_ID (ELEMENT4EGFILTRER4)
    DECLARE_ID (ELEMENT4EGFILTRERR1)
    DECLARE_ID (ELEMENT4EGFILTRERR2)
    
    DECLARE_ID (ELEMENT4EGFILTRE2LEVEL0)
    DECLARE_ID (ELEMENT4EGFILTRE2LEVEL1)
    DECLARE_ID (ELEMENT4EGFILTRE2LEVEL2)
    DECLARE_ID (ELEMENT4EGFILTRE2LEVEL3)
    DECLARE_ID (ELEMENT4EGFILTRE2LEVEL4)
    DECLARE_ID (ELEMENT4EGFILTRE2RL1)
    DECLARE_ID (ELEMENT4EGFILTRE2RL2)
    DECLARE_ID (ELEMENT4EGFILTRE2R1)
    DECLARE_ID (ELEMENT4EGFILTRE2R2)
    DECLARE_ID (ELEMENT4EGFILTRE2R3)
    DECLARE_ID (ELEMENT4EGFILTRE2R4)
    DECLARE_ID (ELEMENT4EGFILTRE2RR1)
    DECLARE_ID (ELEMENT4EGFILTRE2RR2)

    // EG de VOLUME (amplitude) — stockage propre, distinct de l'EG de filtre.
    DECLARE_ID (ELEMENT1SLOPEVOL)
    DECLARE_ID (ELEMENT1EGVOLLEVEL0) DECLARE_ID (ELEMENT1EGVOLLEVEL1) DECLARE_ID (ELEMENT1EGVOLLEVEL2)
    DECLARE_ID (ELEMENT1EGVOLLEVEL3) DECLARE_ID (ELEMENT1EGVOLLEVEL4)
    DECLARE_ID (ELEMENT1EGVOLRL1) DECLARE_ID (ELEMENT1EGVOLRL2)
    DECLARE_ID (ELEMENT1EGVOLR1) DECLARE_ID (ELEMENT1EGVOLR2) DECLARE_ID (ELEMENT1EGVOLR3) DECLARE_ID (ELEMENT1EGVOLR4)
    DECLARE_ID (ELEMENT1EGVOLRR1) DECLARE_ID (ELEMENT1EGVOLRR2)

    DECLARE_ID (ELEMENT2SLOPEVOL)
    DECLARE_ID (ELEMENT2EGVOLLEVEL0) DECLARE_ID (ELEMENT2EGVOLLEVEL1) DECLARE_ID (ELEMENT2EGVOLLEVEL2)
    DECLARE_ID (ELEMENT2EGVOLLEVEL3) DECLARE_ID (ELEMENT2EGVOLLEVEL4)
    DECLARE_ID (ELEMENT2EGVOLRL1) DECLARE_ID (ELEMENT2EGVOLRL2)
    DECLARE_ID (ELEMENT2EGVOLR1) DECLARE_ID (ELEMENT2EGVOLR2) DECLARE_ID (ELEMENT2EGVOLR3) DECLARE_ID (ELEMENT2EGVOLR4)
    DECLARE_ID (ELEMENT2EGVOLRR1) DECLARE_ID (ELEMENT2EGVOLRR2)

    DECLARE_ID (ELEMENT3SLOPEVOL)
    DECLARE_ID (ELEMENT3EGVOLLEVEL0) DECLARE_ID (ELEMENT3EGVOLLEVEL1) DECLARE_ID (ELEMENT3EGVOLLEVEL2)
    DECLARE_ID (ELEMENT3EGVOLLEVEL3) DECLARE_ID (ELEMENT3EGVOLLEVEL4)
    DECLARE_ID (ELEMENT3EGVOLRL1) DECLARE_ID (ELEMENT3EGVOLRL2)
    DECLARE_ID (ELEMENT3EGVOLR1) DECLARE_ID (ELEMENT3EGVOLR2) DECLARE_ID (ELEMENT3EGVOLR3) DECLARE_ID (ELEMENT3EGVOLR4)
    DECLARE_ID (ELEMENT3EGVOLRR1) DECLARE_ID (ELEMENT3EGVOLRR2)

    DECLARE_ID (ELEMENT4SLOPEVOL)
    DECLARE_ID (ELEMENT4EGVOLLEVEL0) DECLARE_ID (ELEMENT4EGVOLLEVEL1) DECLARE_ID (ELEMENT4EGVOLLEVEL2)
    DECLARE_ID (ELEMENT4EGVOLLEVEL3) DECLARE_ID (ELEMENT4EGVOLLEVEL4)
    DECLARE_ID (ELEMENT4EGVOLRL1) DECLARE_ID (ELEMENT4EGVOLRL2)
    DECLARE_ID (ELEMENT4EGVOLR1) DECLARE_ID (ELEMENT4EGVOLR2) DECLARE_ID (ELEMENT4EGVOLR3) DECLARE_ID (ELEMENT4EGVOLR4)
    DECLARE_ID (ELEMENT4EGVOLRR1) DECLARE_ID (ELEMENT4EGVOLRR2)

    // Pitch EG (AFM Element Common, groupe 0x05). Propres propriétés -> ne partage plus
    // celles du filtre (l'ancien PitchEG était un clone de Filter1 lié aux IDs ...EGFILTRE...).
    DECLARE_ID (ELEMENT1SLOPEPITCH)
    DECLARE_ID (ELEMENT1EGPITCHLEVEL0) DECLARE_ID (ELEMENT1EGPITCHLEVEL1) DECLARE_ID (ELEMENT1EGPITCHLEVEL2)
    DECLARE_ID (ELEMENT1EGPITCHLEVEL3) DECLARE_ID (ELEMENT1EGPITCHLEVEL4)
    DECLARE_ID (ELEMENT1EGPITCHRL1) DECLARE_ID (ELEMENT1EGPITCHRL2)
    DECLARE_ID (ELEMENT1EGPITCHR1) DECLARE_ID (ELEMENT1EGPITCHR2) DECLARE_ID (ELEMENT1EGPITCHR3) DECLARE_ID (ELEMENT1EGPITCHR4)
    DECLARE_ID (ELEMENT1EGPITCHRR1) DECLARE_ID (ELEMENT1EGPITCHRR2)

    DECLARE_ID (ELEMENT2SLOPEPITCH)
    DECLARE_ID (ELEMENT2EGPITCHLEVEL0) DECLARE_ID (ELEMENT2EGPITCHLEVEL1) DECLARE_ID (ELEMENT2EGPITCHLEVEL2)
    DECLARE_ID (ELEMENT2EGPITCHLEVEL3) DECLARE_ID (ELEMENT2EGPITCHLEVEL4)
    DECLARE_ID (ELEMENT2EGPITCHRL1) DECLARE_ID (ELEMENT2EGPITCHRL2)
    DECLARE_ID (ELEMENT2EGPITCHR1) DECLARE_ID (ELEMENT2EGPITCHR2) DECLARE_ID (ELEMENT2EGPITCHR3) DECLARE_ID (ELEMENT2EGPITCHR4)
    DECLARE_ID (ELEMENT2EGPITCHRR1) DECLARE_ID (ELEMENT2EGPITCHRR2)

    DECLARE_ID (ELEMENT3SLOPEPITCH)
    DECLARE_ID (ELEMENT3EGPITCHLEVEL0) DECLARE_ID (ELEMENT3EGPITCHLEVEL1) DECLARE_ID (ELEMENT3EGPITCHLEVEL2)
    DECLARE_ID (ELEMENT3EGPITCHLEVEL3) DECLARE_ID (ELEMENT3EGPITCHLEVEL4)
    DECLARE_ID (ELEMENT3EGPITCHRL1) DECLARE_ID (ELEMENT3EGPITCHRL2)
    DECLARE_ID (ELEMENT3EGPITCHR1) DECLARE_ID (ELEMENT3EGPITCHR2) DECLARE_ID (ELEMENT3EGPITCHR3) DECLARE_ID (ELEMENT3EGPITCHR4)
    DECLARE_ID (ELEMENT3EGPITCHRR1) DECLARE_ID (ELEMENT3EGPITCHRR2)

    DECLARE_ID (ELEMENT4SLOPEPITCH)
    DECLARE_ID (ELEMENT4EGPITCHLEVEL0) DECLARE_ID (ELEMENT4EGPITCHLEVEL1) DECLARE_ID (ELEMENT4EGPITCHLEVEL2)
    DECLARE_ID (ELEMENT4EGPITCHLEVEL3) DECLARE_ID (ELEMENT4EGPITCHLEVEL4)
    DECLARE_ID (ELEMENT4EGPITCHRL1) DECLARE_ID (ELEMENT4EGPITCHRL2)
    DECLARE_ID (ELEMENT4EGPITCHR1) DECLARE_ID (ELEMENT4EGPITCHR2) DECLARE_ID (ELEMENT4EGPITCHR3) DECLARE_ID (ELEMENT4EGPITCHR4)
    DECLARE_ID (ELEMENT4EGPITCHRR1) DECLARE_ID (ELEMENT4EGPITCHRR2)

#undef DECLARE_ID
}
/*
Value valueVoiceMode; // mode 1AFM, 2AFM, ...
//Filter Values
Value valueFilter1FreqElement1;
Value valueFilter1FreqElement2;
Value valueFilter1FreqElement3;
Value valueFilter1FreqElement4;

Value valueFilter2FreqElement1;
Value valueFilter2FreqElement2;
Value valueFilter2FreqElement3;
Value valueFilter2FreqElement4;

Value valueFilterResonnanceElement1;
Value valueFilterResonnanceElement2;
Value valueFilterResonnanceElement3;
Value valueFilterResonnanceElement4;

Value valueFilterLfoElement1;
Value valueFilterLfoElement2;
Value valueFilterLfoElement3;
Value valueFilterLfoElement4;

Value valueFilterVelocityElement1;
Value valueFilterVelocityElement2;
Value valueFilterVelocityElement3;
Value valueFilterVelocityElement4;

Value valueFilterSlopeElement1;
Value valueFilterSlopeElement2;
Value valueFilterSlopeElement3;
Value valueFilterSlopeElement4;

Value valueFilter1ModeElement1;
Value valueFilter1ModeElement2;
Value valueFilter1ModeElement3;
Value valueFilter1ModeElement4;

Value valueFilter2ModeElement1;
Value valueFilter2ModeElement2;
Value valueFilter2ModeElement3;
Value valueFilter2ModeElement4;

Value valueFilter1ControlElement1;
Value valueFilter1ControlElement2;
Value valueFilter1ControlElement3;
Value valueFilter1ControlElement4;

Value valueFilter2ControlElement1;
Value valueFilter2ControlElement2;
Value valueFilter2ControlElement3;
Value valueFilter2ControlElement4;

Value valueFilterLevel0Element1;
Value valueFilterLevel0Element2;
Value valueFilterLevel0Element3;
Value valueFilterLevel0Element4;

Value valueFilterLevel1Element1;
Value valueFilterLevel1Element2;
Value valueFilterLevel1Element3;
Value valueFilterLevel1Element4;

Value valueFilterLevel2Element1;
Value valueFilterLevel2Element2;
Value valueFilterLevel2Element3;
Value valueFilterLevel2Element4;

Value valueFilterLevel3Element1;
Value valueFilterLevel3Element2;
Value valueFilterLevel3Element3;
Value valueFilterLevel3Element4;

Value valueFilterLevel4Element1;
Value valueFilterLevel4Element2;
Value valueFilterLevel4Element3;
Value valueFilterLevel4Element4;

Value valueFilterRate0Element1;
Value valueFilterRate0Element2;
Value valueFilterRate0Element3;
Value valueFilterRate0Element4;

Value valueFilterRate1Element1;
Value valueFilterRate1Element2;
Value valueFilterRate1Element3;
Value valueFilterRate1Element4;
*/
// `inline` : défini dans un header mais une seule instance (ODR-safe, multi-TU/CMake).
inline ValueTree   valueTreeVoice ("Sysex77");
